In [10]:
import pandas as pd
import numpy as np

In [2]:
# load data2
data2 = pd.read_csv('data2.csv')

data2

,ID,Wilaya,University,Level of your study,How did you hear of CSE Around Algeria?,Select the workshop you wish to attend,Rate your knowledge in the field of the workshop
0,1,Alger,Autre,1 cs / L3,Recommended by a friend or a colleague,Intro to cloud,3
1,2,Alger,University of Algiers 1,2 cp / L2,Recommended by a friend or a colleague,Intro to cloud,3
2,3,Alger,Autre,2 cp / L2,CSE's social media,Intro to cloud,2
3,4,Alger,Autre,2 cs / Master 1,CSE's social media,Intro to cloud,3
4,5,Alger,Autre,1 cp / L1,CSE's social media,Intro to cloud,2
...,...,...,...,...,...,...,...
116,117,Alger,USTHB,1 cp / L1,CSE's social media,Dev WEB : intro to HTML CSS,1
117,118,Alger,USTHB,1 cp / L1,Your local partner of CSE Around Algeria,Dev WEB : intro to HTML CSS,1
118,119,Alger,Autre,3 cs/ Master 2,Recommended by a friend or a colleague,Dev WEB : intro to HTML CSS,1
119,120,Alger,Autre,2 cp / L2,CSE's social media,Intro to machine learning an AI,1
120,121,Alger,USTHB,1 cp / L1,CSE's social media,Dev WEB : intro to HTML CSS,1

In [4]:
# add IDs to the data2

data2['ID'] = np.arange(1, len(data2) + 1)

data2.to_csv('data2.csv', index=False)

In [5]:
# put the ID column in the first position
cols = data2.columns.tolist()
cols = cols[-1:] + cols[:-1]
data2 = data2[cols]

#save data2
data2.to_csv('data2.csv', index=False)

data2

,ID,Wilaya,University,Level of your study,How did you hear of CSE Around Algeria?,Select the workshop you wish to attend,Rate your knowledge in the field of the workshop
0,1,Alger,Akli muhand oulhadj Bouira,1 cs / L3 / 3 ème année,Recommended by a friend or a colleague,"Dev WEB ""intro to HTML CSS"", Alger",3
1,2,Alger,Algiers university 1,2 cp / L2 / 2 ème année,Recommended by a friend or a colleague,"Dev WEB ""intro to HTML CSS"", Alger",3
2,3,Alger,Autre,2 cp / L2 / 2 ème année,CSE's social media,"Dev WEB ""intro to HTML CSS"", Alger",2
3,4,Alger,Autre,2 cs / Master 1 / 4 ème année,CSE's social media,"Dev WEB ""intro to HTML CSS"", Alger",3
4,5,Alger,Autre,1 cp / L1 / 1 ère année,CSE's social media,"Dev WEB ""intro to HTML CSS"", Alger",2
...,...,...,...,...,...,...,...
116,117,Alger,Usthb,1 cp / L1 / 1 ère année,CSE's social media,"Dev WEB ""intro to HTML CSS"", Alger",1
117,118,Alger,Usthb university science technology houari Bou...,1 cp / L1 / 1 ère année,By 1001 tech Instagram,"Dev WEB ""intro to HTML CSS"", Alger",1
118,119,Alger,المدرسة الوطنية للمانجمنت وإدارة الصحة,6 ème année,Recommended by a friend or a colleague,"Dev WEB ""intro to HTML CSS"", Alger",1
119,120,Alger,ثانوي,bac,CSE's social media,"Intro to machine learning an AI, Medea",1
120,121,Alger,usthb,1 cp / L1 / 1 ère année,CSE's social media,"Dev WEB ""intro to HTML CSS"", Alger",1

In [8]:
# count the number of unique values in each column
data = pd.read_csv('data2.csv')

data.nunique()

# get count of each value in all columns
for col in data.columns[1:]:
    print(data[col].value_counts())

Wilaya
Alger    121
Name: count, dtype: int64
University
Faculty of medicine  Ziania    49
ESI                            36
USTHB                          22
University of Algiers 1        14
Name: count, dtype: int64
Level of your study
2 cp / L2          42
1 cp / L1          42
2 cs / Master 1    20
1 cs / L3          17
Name: count, dtype: int64
How did you hear of CSE Around Algeria?
CSE's social media                          67
Your local partner of CSE Around Algeria    33
Recommended by a friend or a colleague      21
Name: count, dtype: int64
Select the workshop you wish to attend
Dev WEB : intro to HTML CSS        48
Intro to cloud                     40
Intro to machine learning an AI    33
Name: count, dtype: int64
Rate your knowledge in the field of the workshop
1    67
2    30
3    24
Name: count, dtype: int64

In [57]:
# one hot encode data_encoded , except the ID and city column
data_encoded = pd.get_dummies(data, columns=data.columns[2:])

#save data_encoded

data_encoded.to_csv('data_encoded.csv', index=False)

In [14]:
data = pd.read_csv('../AFC/data.csv')

data

,year,Dev WEB : intro to HTML CSS,Intro to cloud,Intro to machine learning an AI
0,1 cp / L1,18,12,12
1,1 cs / L3,6,8,3
2,2 cp / L2,16,14,12
3,2 cs / Master 1,8,6,6